[project]
name = "calgen"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
  "pydantic",
  "click",
  "drawsvg[all]",
  "pyyaml",
  "holidays",
]
license = {file = "LICENSE.md"}
authors = [
  {name = "Mateusz Maciaś", email = "mmacias@sinevo.pl"},
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pypdf",
  "black",
  "flake8",
  "isort",
  "mypy",
  "pre-commit",
  "build",
  "wheel",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
calgen = "calgen.cli.calgen:main"


[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["drawsvg.*", "cairosvg", "yaml"]
ignore_missing_imports = true

[tool.isort]
profile = "black"
